Add TEST_DATABASE_URL to the default .env
redwoodjs/create-redwood-app pull request #123
Opened 2021-01-10 12:37 UTC by jvanbaarsen

Currently it is a bit implicit that you can use the `TEST_DATABASE_URL`
env variable. I was able to figure this out by looking through the
source code, and since someone posted this on the issue tracker it means
more people find it a bit implicit.

Fixes: https://github.com/redwoodjs/redwood/issues/1620

2021-01-10 14:58 UTC, dthyresson commented
Should `TEST_DATABASE_URL` be included in the .example and .defaults as well?

Since

```
# schema.prisma defaults
DATABASE_URL=file:./dev.db
```

is in defaults? Would `TEST_DATABASE_URL` be set to the same? 

Or a different database?

Perhaps a comment describes its purpose?

2021-01-10 15:22 UTC, jvanbaarsen commented
@dthyresson I was in doubt about this. The reason for me not to include it was that the DATABASE_URL in `.env` is pretty much specific for Postgresql. This is also the only provider where you need to set the `TEST_DATABASE_URL`. For SQLite this works out of the box (Because it will just create a .db file in the temp directory).

What I want to achieve with this is mostly awareness that this option is available for you to set, since this caused me a bunch of confusion.

2021-01-10 16:27 UTC, dthyresson commented
> I was in doubt about this.

Thanks @jvanbaarsen -- perhaps @thedavidprice @cannikin or @peterp can determine if it should or not. Agree that the goals is not to be confused if you need to test against a postgres database

2021-01-11 17:10 UTC, cannikin commented
My first thought is to add to `.env.defaults` with the current default path of `.redwood/test.db` but commented out with a note about usage:

```bash
# These environment variables will be used by default if you do not create any
# yourself in .env. This file should be safe to check into your version control
# system. Any custom values should go in .env and .env should *not* be checked
# into version control.

# schema.prisma defaults
DATABASE_URL=file:./dev.db

# location of the test database for api service scenarios (defaults to ./.redwood/test.db it not set)
# TEST_DATABASE_URL=file:./.redwood/test.db

# disables Prisma CLI update notifier
PRISMA_HIDE_UPDATE_MESSAGE=true
```

2021-01-12 06:54 UTC, thedavidprice commented
I +1 Rob's suggestion above.

Also, we most definitely need to finish the [Test Documentation](https://github.com/redwoodjs/redwoodjs.com/pull/186)! I've added a note about this on that PR as well.

2021-01-12 23:25 UTC, thedavidprice requested changes
Instead of adding to `.env`, add to `.env.defaults` with the current default path of `.redwood/test.db` but commented out with a note about usage:

```
# These environment variables will be used by default if you do not create any
# yourself in .env. This file should be safe to check into your version control
# system. Any custom values should go in .env and .env should *not* be checked
# into version control.

# schema.prisma defaults
DATABASE_URL=file:./dev.db

# location of the test database for api service scenarios (defaults to ./.redwood/test.db it not set)
# TEST_DATABASE_URL=file:./.redwood/test.db

# disables Prisma CLI update notifier
PRISMA_HIDE_UPDATE_MESSAGE=true
```

2021-01-13 00:01 UTC, cannikin commented
Yes, this should go in `.env.defaults` please!

2021-01-13 09:11 UTC, jvanbaarsen commented
Allright! I'll update this PR 👍

2021-01-13 19:15 UTC, thedavidprice requested changes

2021-01-13 19:15 UTC, thedavidprice commented on .env
>  # BINARY_TARGET=rhel-openssl-1.0.x
```suggestion

```
Oops, this isn't needed anymore. Just cleaning up.

And great idea to add commented example here!

2021-01-13 19:17 UTC, thedavidprice approved these changes

2021-01-13 19:17 UTC, merged